config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('item.urls', namespace='items')),
    path('', include('order.urls', namespace='orders')),
]

item/urls.py
from django.urls import path

from item.apps import ItemConfig
from item.views import get_item, buy_item

app_name = ItemConfig.name

urlpatterns = [
    path('item/<int:item_id>', get_item, name='get_item'),
    path('buy/<int:item_id>', buy_item, name='buy_item'),
]

order/urls.py
from django.urls import path

from order.apps import OrderConfig
from order.views import CreateOrderView, get_successful_payment_url

app_name = OrderConfig.name

urlpatterns = [
    path('order/create', CreateOrderView.as_view(), name='create_order'),
    path('order/successful_payment', get_successful_payment_url, name='successful_payment'),
]

order/models.py
from django.db import models

from item.models import Item, NULLABLE
from pricing.models.discount import Discount
from pricing.models.tax import Tax


class Order(models.Model):
    PAYMENT_STATUS = [
        ('unpaid', 'Unpaid'),
        ('paid', 'Paid'),
    ]

    items = models.ManyToManyField(Item, verbose_name='order_items', related_name='orders')
    tax = models.ForeignKey(Tax, verbose_name='order_tax', related_name='orders', on_delete=models.SET_NULL, **NULLABLE)
    discount = models.ForeignKey(
        Discount, verbose_name='order_discount', related_name='orders', on_delete=models.SET_NULL, **NULLABLE)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='created_at')
    total_price = models.DecimalField(default=0.0, decimal_places=2, max_digits=15, verbose_name='total_price')
    currency = models.CharField(verbose_name='currency', max_length=3, **NULLABLE)
    payment_status = models.CharField(
        verbose_name='payment_status', choices=PAYMENT_STATUS, default='unpaid', max_length=6)

    def __str__(self):
        return f'Order {self.pk} - {self.created_at}'

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

order/forms.py
from django import forms

from item.models import Item
from order.models import Order
from pricing.models.discount import Discount
from pricing.models.tax import Tax


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            if field_name == 'items':
                self.fields[field_name] = forms.ModelMultipleChoiceField(
                    queryset=Item.objects.all(), )
                self.fields[field_name].widget.attrs['class'] = 'form-control'
            if field_name == 'discount':
                self.fields[field_name] = forms.ModelChoiceField(
                    queryset=Discount.objects.all(), required=False)
                self.fields[field_name].widget.attrs['class'] = 'form-control'
            if field_name == 'tax':
                self.fields[field_name] = forms.ModelChoiceField(
                    queryset=Tax.objects.all(), required=False)
                self.fields[field_name].widget.attrs['class'] = 'form-control'

    class Meta:
        model = Order
        exclude = ('created_at', 'total_price', 'payment_status',)

order/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render
from django.views import generic

from config.settings import SMALLEST_CURRENCY_UNIT_RATIO
from order.service import ProjectStripeSession
from order.forms import OrderForm
from order.models import Order
from order.tasks import set_payment_status_check_schedule, set_disabler_schedule


class CreateOrderView(generic.CreateView):
    model = Order
    form_class = OrderForm
    extra_context = {'page_title': 'Create Order'}
    template_name = 'order/create_order.html'

    def get_success_url(self):
        """
        Sets the Stripe Checkout Session url as the successful url for the Order creating.
        The url is collected from the self.request.session object.
        """
        return self.request.session.get('checkout_url')

    def form_valid(self, form):
        """
        Checks whether the form is valid, assigns the 'total_price', 'currency' fields values to the Order instance,
        sets the schedule of the periodic task (set_payment_status_check_schedule) to monitor the payment_status of the
        Stripe Checkout Session, and the schedule of the one-off task (set_disabler_schedule) to disable the
        set_payment_status periodic task if the Order is paid of the payment expired (exp time - 30 minutes).
        """
        self.object = form.save()
        if form.is_valid():
            items = form.cleaned_data.get('items', [])
            discount = form.cleaned_data.get('discount', None)
            tax = form.cleaned_data.get('tax', None)

            if items:
                project_stripe_obj = ProjectStripeSession(
                    items=items,
                    discount=discount,
                    tax=tax)
                stripe_session = project_stripe_obj.make_session()
                self.object.total_price = stripe_session['amount_total'] / SMALLEST_CURRENCY_UNIT_RATIO
                self.object.currency = stripe_session['currency']
                self.object.save()

                self.request.session['checkout_url'] = stripe_session['url']

                set_payment_status_check_schedule.delay(order_id=self.object.pk, stripe_session_id=stripe_session['id'])
                set_disabler_schedule.delay(order_id=self.object.pk)

                return super().form_valid(form)
            else:
                ValidationError('Select items for your order')


def get_successful_payment_url(request):
    """
    A simple custom successful payment page.
    """
    context = {'page_title': 'Successful payment'}
    return render(request, 'order/success_url.html', context)

order/templates/order/create_order.html
{% extends 'item/base.html'%}
{% block content %}

<header>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal text-body-emphasis">Create an order</h1>
    </div>
</header>


<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">

        <div class="col mx-auto">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Order details</h4>
                </div>
                <form class="form-control" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="card-body">
                        <div class="form-group">
                            {{ form.items.label_tag }} {{ form.items }}
                            {{ form.discount.label_tag }} {{ form.discount }}
                            {{ form.tax.label_tag }} {{ form.tax }}
                        </div>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="w-100 btn btn-lg btn-primary" name="buy_order">Buy</button>
                    </div>
                </form>
            </div>
        </div>

    </div>
</main>
{% endblock %}

order/templates/order/success_url.html
{% extends 'item/base.html'%}
{% block content %}


<main>
    <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">

        <div class="col mx-auto">
            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Payment status: Successful</h4>
                </div>
                <div class="card-body">
                </div>
                <div class="card-footer">
                    <a href="{% url 'order:create_order' %}"
                       class="link-body-emphasis d-inline-flex text-decoration-none rounded">Create new order</a>
                </div>
            </div>
        </div>

    </div>
</main>
{% endblock %}